-- ===========================================================================
-- Does this database still match schema.sql?
--
-- verify.sql asks "did the patches land". This asks the question that actually
-- bit us: has schema.sql grown a column that no patch ever added?
--
-- That is not a hypothetical. `change_requests.end_date` was added to
-- schema.sql and to every function that reads it, but never to a patch — so on
-- any database brought forward with patches rather than rebuilt, every call to
-- ensure_daily_trips() raised "column c.end_date does not exist" and the app,
-- which swallows that error on purpose, showed an empty day instead. It cost
-- two weeks of "no trips today" before anyone saw the exception.
--
-- Existence checks cannot find this. plpgsql resolves column names when a
-- statement RUNS, not when the function is created, so a function that
-- references a column nobody ever created is created perfectly happily and
-- fails later, in production, quietly.
--
-- Paste the whole file into the Supabase SQL editor. One green row means the
-- 26 tables and 218 columns in schema.sql all exist here. Anything else is
-- a column some function is already written against.
--
-- Generated from schema.sql. Regenerate it when the schema changes.
-- ===========================================================================

with expected(tbl, col) as (values
  ('organization', 'id'),
  ('organization', 'name'),
  ('organization', 'logo_url'),
  ('organization', 'gps_enabled'),
  ('organization', 'payments_enabled'),
  ('organization', 'morning_cutoff'),
  ('organization', 'afternoon_cutoff'),
  ('organization', 'attendance_mode'),
  ('organization', 'watchdog_enabled'),
  ('organization', 'watchdog_trip_start_min'),
  ('organization', 'watchdog_stop_arrival_min'),
  ('organization', 'watchdog_waiting_min'),
  ('organization', 'watchdog_trip_max_min'),
  ('organization', 'watchdog_onboard_min'),
  ('organization', 'undo_window_sec'),
  ('organization', 'time_zone'),
  ('profiles', 'id'),
  ('profiles', 'role'),
  ('profiles', 'full_name'),
  ('profiles', 'email'),
  ('profiles', 'phone'),
  ('profiles', 'status'),
  ('profiles', 'expo_push_token'),
  ('profiles', 'created_at'),
  ('invites', 'id'),
  ('invites', 'code'),
  ('invites', 'role'),
  ('invites', 'full_name'),
  ('invites', 'email'),
  ('invites', 'note'),
  ('invites', 'created_by'),
  ('invites', 'created_at'),
  ('invites', 'expires_at'),
  ('invites', 'used_by'),
  ('invites', 'used_at'),
  ('invites', 'revoked_at'),
  ('schools', 'id'),
  ('schools', 'name'),
  ('schools', 'address'),
  ('schools', 'lat'),
  ('schools', 'lng'),
  ('hubs', 'id'),
  ('hubs', 'name'),
  ('hubs', 'address'),
  ('hubs', 'lat'),
  ('hubs', 'lng'),
  ('hubs', 'active'),
  ('students', 'student_id'),
  ('students', 'school_id'),
  ('students', 'grade'),
  ('students', 'morning_hub_id'),
  ('students', 'afternoon_hub_id'),
  ('guardian_links', 'id'),
  ('guardian_links', 'parent_id'),
  ('guardian_links', 'student_id'),
  ('guardian_links', 'status'),
  ('guardian_links', 'requested_by'),
  ('guardian_links', 'created_at'),
  ('vehicles', 'id'),
  ('vehicles', 'label'),
  ('vehicles', 'plate'),
  ('vehicles', 'capacity'),
  ('vehicles', 'active'),
  ('vehicle_devices', 'vehicle_id'),
  ('vehicle_devices', 'device_key'),
  ('vehicle_devices', 'board_code'),
  ('route_templates', 'id'),
  ('route_templates', 'name'),
  ('route_templates', 'type'),
  ('route_templates', 'school_id'),
  ('route_templates', 'operating_weekdays'),
  ('route_templates', 'default_driver_id'),
  ('route_templates', 'default_vehicle_id'),
  ('route_templates', 'active'),
  ('route_templates', 'created_at'),
  ('route_stops', 'id'),
  ('route_stops', 'route_id'),
  ('route_stops', 'seq'),
  ('route_stops', 'hub_id'),
  ('route_stops', 'school_id'),
  ('route_stops', 'planned_arrival'),
  ('route_stops', 'planned_departure'),
  ('route_assignments', 'id'),
  ('route_assignments', 'route_id'),
  ('route_assignments', 'student_id'),
  ('route_assignments', 'pickup_stop_id'),
  ('route_assignments', 'dropoff_stop_id'),
  ('daily_trips', 'id'),
  ('daily_trips', 'route_id'),
  ('daily_trips', 'date'),
  ('daily_trips', 'driver_id'),
  ('daily_trips', 'vehicle_id'),
  ('daily_trips', 'status'),
  ('daily_trips', 'started_at'),
  ('daily_trips', 'ended_at'),
  ('daily_trips', 'delay_minutes'),
  ('daily_trips', 'delay_reason'),
  ('student_trip_status', 'id'),
  ('student_trip_status', 'trip_id'),
  ('student_trip_status', 'student_id'),
  ('student_trip_status', 'status'),
  ('student_trip_status', 'pickup_stop_id'),
  ('student_trip_status', 'dropoff_stop_id'),
  ('student_trip_status', 'board_time'),
  ('student_trip_status', 'dropoff_time'),
  ('student_trip_status', 'note'),
  ('student_trip_status', 'boarding_code'),
  ('student_trip_status', 'updated_by'),
  ('student_trip_status', 'updated_at'),
  ('trip_stop_progress', 'id'),
  ('trip_stop_progress', 'trip_id'),
  ('trip_stop_progress', 'stop_id'),
  ('trip_stop_progress', 'arrived_at'),
  ('trip_stop_progress', 'departed_at'),
  ('trip_stop_progress', 'departed_with_unresolved'),
  ('trip_stop_progress', 'skipped'),
  ('arrival_alerts', 'id'),
  ('arrival_alerts', 'trip_id'),
  ('arrival_alerts', 'stop_id'),
  ('arrival_alerts', 'minutes'),
  ('arrival_alerts', 'sent_at'),
  ('change_requests', 'id'),
  ('change_requests', 'student_id'),
  ('change_requests', 'date'),
  ('change_requests', 'end_date'),
  ('change_requests', 'kind'),
  ('change_requests', 'reason'),
  ('change_requests', 'requested_by'),
  ('change_requests', 'approval'),
  ('change_requests', 'reviewed_by'),
  ('change_requests', 'reviewed_at'),
  ('change_requests', 'review_note'),
  ('change_requests', 'created_at'),
  ('assignment_requests', 'id'),
  ('assignment_requests', 'student_id'),
  ('assignment_requests', 'requested_by'),
  ('assignment_requests', 'school_id'),
  ('assignment_requests', 'morning_hub_id'),
  ('assignment_requests', 'afternoon_hub_id'),
  ('assignment_requests', 'reason'),
  ('assignment_requests', 'status'),
  ('assignment_requests', 'reviewed_by'),
  ('assignment_requests', 'reviewed_at'),
  ('assignment_requests', 'review_note'),
  ('assignment_requests', 'created_at'),
  ('incidents', 'id'),
  ('incidents', 'trip_id'),
  ('incidents', 'student_id'),
  ('incidents', 'driver_id'),
  ('incidents', 'kind'),
  ('incidents', 'severity'),
  ('incidents', 'description'),
  ('incidents', 'resolved_at'),
  ('incidents', 'resolved_by'),
  ('incidents', 'created_at'),
  ('announcements', 'id'),
  ('announcements', 'title'),
  ('announcements', 'body'),
  ('announcements', 'route_id'),
  ('announcements', 'student_id'),
  ('announcements', 'created_by'),
  ('announcements', 'created_at'),
  ('notifications', 'id'),
  ('notifications', 'user_id'),
  ('notifications', 'title'),
  ('notifications', 'body'),
  ('notifications', 'kind'),
  ('notifications', 'read_at'),
  ('notifications', 'created_at'),
  ('notifications', 'delivery_state'),
  ('notifications', 'delivery_detail'),
  ('notifications', 'delivered_at'),
  ('notifications', 'requires_ack'),
  ('notifications', 'acknowledged_at'),
  ('notifications', 'acknowledged_by'),
  ('audit_logs', 'id'),
  ('audit_logs', 'entity_type'),
  ('audit_logs', 'entity_id'),
  ('audit_logs', 'action'),
  ('audit_logs', 'old_value'),
  ('audit_logs', 'new_value'),
  ('audit_logs', 'reason'),
  ('audit_logs', 'changed_by'),
  ('audit_logs', 'changed_at'),
  ('watchdog_alerts', 'id'),
  ('watchdog_alerts', 'trip_id'),
  ('watchdog_alerts', 'stop_id'),
  ('watchdog_alerts', 'student_id'),
  ('watchdog_alerts', 'notification_id'),
  ('watchdog_alerts', 'kind'),
  ('watchdog_alerts', 'detail'),
  ('watchdog_alerts', 'raised_at'),
  ('watchdog_alerts', 'notified_at'),
  ('watchdog_alerts', 'resolved_at'),
  ('watchdog_alerts', 'resolved_by'),
  ('watchdog_alerts', 'resolution'),
  ('vehicle_locations', 'id'),
  ('vehicle_locations', 'vehicle_id'),
  ('vehicle_locations', 'trip_id'),
  ('vehicle_locations', 'lat'),
  ('vehicle_locations', 'lng'),
  ('vehicle_locations', 'heading'),
  ('vehicle_locations', 'speed'),
  ('vehicle_locations', 'source'),
  ('vehicle_locations', 'recorded_at'),
  ('invoices', 'id'),
  ('invoices', 'student_id'),
  ('invoices', 'period'),
  ('invoices', 'amount_cents'),
  ('invoices', 'due_date'),
  ('invoices', 'status'),
  ('invoices', 'paid_at'),
  ('invoices', 'note'),
  ('account_removals', 'id'),
  ('account_removals', 'email'),
  ('account_removals', 'reason'),
  ('account_removals', 'removed_by'),
  ('account_removals', 'created_at')
),
missing as (
  select e.tbl, e.col,
         case
           when not exists (
             select 1 from information_schema.tables
             where table_schema = 'public' and table_name = e.tbl)
           then 'TABLE MISSING '
           else 'column missing'
         end as what
  from expected e
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name  = e.tbl
      and column_name = e.col)
)
select line from (
  select 0 as ord,
         case when count(*) = 0
              then '✅ schema.sql and this database agree — 26 tables, 218 columns'
              else '❌ ' || count(*)::text || ' missing. Every one of them is a column'
                   || ' some function already reads.'
         end as line
  from missing
  union all
  select 1, '   ' || what || ' → ' || tbl || '.' || col from missing
) x
order by ord, line;
